---
- name: Deploy Frontend (Nginx)
  hosts: web
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Copy frontend files to web root
      copy:
        src: frontend/
        dest: /var/www/html/
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
