- name: Deploy Frontend
  hosts: frontend
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy frontend files
      copy:
        src: ../../app/frontend/
        dest: /var/www/html/
        mode: 0755

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
