---
- name: Deploy Backend (Node.js)
  hosts: app
  become: yes
  vars:
    backend_dir: /opt/backend
    node_version: "16"

  tasks:
    - name: Ensure curl and required packages are installed
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present
        update_cache: yes

    - name: Add Node.js APT repository
      shell: curl -fsSL https://deb.nodesource.com/setup_{{ node_version }}.x | bash -
      args:
        executable: /bin/bash
      register: node_setup
      changed_when: "'Node.js' in node_setup.stdout or node_setup.rc == 0"

    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Create backend directory
      file:
        path: "{{ backend_dir }}"
        state: directory
        mode: '0755'

    - name: Copy backend app files
      copy:
        src: ../../app/backend/
        dest: "{{ backend_dir }}/"
        mode: '0755'
        owner: root
        group: root

    - name: Install npm dependencies
      command: npm ci
      args:
        chdir: "{{ backend_dir }}"

    - name: Create systemd service for backend
      copy:
        dest: /etc/systemd/system/backend.service
        content: |
          [Unit]
          Description=Node.js Backend App
          After=network.target

          [Service]
          Environment=DB_HOST={{ hostvars['db1']['ansible_host'] }}
          WorkingDirectory={{ backend_dir }}
          ExecStart=/usr/bin/node server.js
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target
      notify: Restart backend service

  handlers:
    - name: Restart backend service
      systemd:
        name: backend
        state: restarted
        enabled: yes